# Generated by Django 4.2.3 on 2023-12-05 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joke_app', '0002_alter_joke_author_alter_joke_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpDownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
                ('downvote', models.BooleanField()),
                ('joke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updownvote_joke', to='joke_app.joke')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updownvote_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
