# Generated by Django 4.2.3 on 2023-12-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
