# Generated by Django 4.2.3 on 2023-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='display_name',
            field=models.CharField(default='Chuckle Head', unique=True),
            preserve_default=False,
        ),
    ]
