# Generated by Django 4.2.3 on 2023-12-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_client_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='display_name',
        ),
    ]
