# Generated by Django 4.2.3 on 2023-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_client_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='display_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
