# Generated by Django 4.2.3 on 2023-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokeimage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokeimage',
            name='api_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jokeimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
